#!/bin/sh

echo 'start_file=start_x.elf' >> /boot/config.txt
echo 'dtparam=i2c_vc=on' >> /boot/config.txt
echo 'dtparam=i2c_arm=on' >> /boot/config.txt
echo 'modprobe i2c_bcm2708' >> /etc/rc.local
echo 'modprobe i2c_dev' >> /etc/rc.local

